<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Change-making problem</title>
    <link href="/css/style.css" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]><script type="text/javascript" src="/js/html5shiv.js"></script><![endif]-->
</head>

<body>

    <header>
        <div class="wrapper">
            <h2>Change-making problem</h2>
        </div>
    </header>
    
    <div id="content">
    <?php echo $this->content; ?>
    </div> 
    
    <footer>
        <div class="wrapper">
        </div>
    </footer>

</body>
</html>
