<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Change-making problem</title>
    <link href="/css/style.css" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]><script type="text/javascript" src="/js/html5shiv.js"></script><![endif]-->
</head>

<body>

	<header>
		<div class="wrapper">
			<h2>Change-making problem</h2>
		</div>
	</header>
	
	<div id="content">
    <?php echo $this->content; ?>
	</div> 
	
	<footer>
		<div class="wrapper">
			<ul class="contact">
				<li><a href="https://plus.google.com/u/0/118303929003102356781"><img src="/img/googleplus.png" alt="Google Plus"></a></li>
				<li><a href="https://twitter.com/fedecarg"><img src="/img/twitter.png" alt="Twitter"></a></li>
				<li><a href="http://www.linkedin.com/in/fedecarg"><img src="/img/linkedin.png" alt="LinkedIn"></a></li>
				<li><a href="http://vimeo.com/fedecarg"><img src="/img/vimeo.png" alt="Vimeo"></a></li>
			</ul>
		</div>
		<p>Get in touch</p>
	</footer>

</body>
</html>
